"""empty message

Revision ID: 0c1081e67952
Revises: 45e8ddcc9880
Create Date: 2025-01-14 22:53:27.578994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1081e67952'
down_revision = '45e8ddcc9880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_reservation', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_reservation'], ['id_user'])

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_reservation',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_reservation',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_reservation')

    # ### end Alembic commands ###
