"""empty message

Revision ID: 45711dd0d48d
Revises: b925a49a8973
Create Date: 2025-01-14 21:39:28.657045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45711dd0d48d'
down_revision = 'b925a49a8973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_hotel')
    )
    op.create_table('hotel__admin__package',
    sa.Column('id_admin_package', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.Enum('básico', 'prioritario', name='package_name_enum'), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_admin_package')
    )
    op.create_table('payment',
    sa.Column('id_payment', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_payment')
    )
    op.create_table('reservation',
    sa.Column('id_reservation', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('reservation_payment', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_reservation')
    )
    op.create_table('stay__package',
    sa.Column('id_hotel_package', sa.Integer(), nullable=False),
    sa.Column('hotel_package_name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_hotel_package')
    )
    op.create_table('favorites',
    sa.Column('id_favorites', sa.Integer(), nullable=False),
    sa.Column('user_favorites', sa.Integer(), nullable=True),
    sa.Column('hotel_favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_favorites'], ['hotel.id_hotel'], ),
    sa.ForeignKeyConstraint(['user_favorites'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorites')
    )
    op.create_table('stay__history',
    sa.Column('id_stay_history', sa.Integer(), nullable=False),
    sa.Column('user_stay_history', sa.Integer(), nullable=True),
    sa.Column('package_stay_history', sa.Integer(), nullable=True),
    sa.Column('reservation_stay_history', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_stay_history'], ['stay__package.id_hotel_package'], ),
    sa.ForeignKeyConstraint(['reservation_stay_history'], ['reservation.id_reservation'], ),
    sa.ForeignKeyConstraint(['user_stay_history'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_stay_history')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('user_type', sa.Enum('cliente', 'hotel', 'admin', name='user_type_enum'), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('user_type')
        batch_op.drop_column('name')

    op.drop_table('stay__history')
    op.drop_table('favorites')
    op.drop_table('stay__package')
    op.drop_table('reservation')
    op.drop_table('payment')
    op.drop_table('hotel__admin__package')
    op.drop_table('hotel')
    # ### end Alembic commands ###
