"""empty message

Revision ID: 749d55fd05a0
Revises: db0a46c5e3c4
Create Date: 2025-02-01 03:31:53.535709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749d55fd05a0'
down_revision = 'db0a46c5e3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('payment_id')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
