"""added profile picture to user

Revision ID: 75e4f98d0fb7
Revises: fb7e639e4a83
Create Date: 2025-02-11 02:05:21.053241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e4f98d0fb7'
down_revision = 'fb7e639e4a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
