"""empty message

Revision ID: 9fd8ce6d85b0
Revises: 
Create Date: 2025-01-28 00:55:24.140439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd8ce6d85b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel__admin__package',
    sa.Column('id_admin_package', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_admin_package')
    )
    op.create_table('stay__package',
    sa.Column('id_hotel_package', sa.Integer(), nullable=False),
    sa.Column('hotel_package_name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_hotel_package')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('user_type', sa.Enum('cliente', 'hotel', 'admin', name='user_type_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hotel',
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_hotel')
    )
    op.create_table('payment',
    sa.Column('id_payment', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('user_reservation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_reservation'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_payment')
    )
    op.create_table('reservation',
    sa.Column('id_reservation', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('reservation_payment', sa.Integer(), nullable=False),
    sa.Column('user_reservation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_reservation'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_reservation')
    )
    op.create_table('user__hotel__admin__package',
    sa.Column('id_user_admin_package', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_hotel_Admin_Package', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hotel_Admin_Package'], ['hotel__admin__package.id_admin_package'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_admin_package')
    )
    op.create_table('favorites',
    sa.Column('id_favorites', sa.Integer(), nullable=False),
    sa.Column('user_favorites', sa.Integer(), nullable=True),
    sa.Column('hotel_favorites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_favorites'], ['hotel.id_hotel'], ),
    sa.ForeignKeyConstraint(['user_favorites'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorites')
    )
    op.create_table('stay__history',
    sa.Column('id_stay_history', sa.Integer(), nullable=False),
    sa.Column('user_stay_history', sa.Integer(), nullable=True),
    sa.Column('package_stay_history', sa.Integer(), nullable=True),
    sa.Column('reservation_stay_history', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_stay_history'], ['stay__package.id_hotel_package'], ),
    sa.ForeignKeyConstraint(['reservation_stay_history'], ['reservation.id_reservation'], ),
    sa.ForeignKeyConstraint(['user_stay_history'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_stay_history')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stay__history')
    op.drop_table('favorites')
    op.drop_table('user__hotel__admin__package')
    op.drop_table('reservation')
    op.drop_table('payment')
    op.drop_table('hotel')
    op.drop_table('user')
    op.drop_table('stay__package')
    op.drop_table('hotel__admin__package')
    # ### end Alembic commands ###
