"""empty message

Revision ID: b925a49a8973
Revises: 28960976e1b0
Create Date: 2025-01-11 03:04:13.351760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b925a49a8973'
down_revision = '28960976e1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('last_name')
        batch_op.drop_column('nombre')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
