"""empty message

Revision ID: da3daaa3fa99
Revises: 6610517c6318
Create Date: 2025-01-22 02:12:52.100265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3daaa3fa99'
down_revision = '6610517c6318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hotel_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
